spring:
  application:
    name: telegrambot]
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_bot?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      auto-commit: false
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.hibernate.default_schema: public
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    default-schema: public
    change-log: classpath:/db.changelog/master.xml
    database-change-log-lock-table: _databasechangeloglock
    database-change-log-table: _databasechangelog


bot:
  name: "PinsBot"
  token: fd
